package BeatBoxify.Repositories;

import org.springframework.data.jpa.repository.JpaRepository;

import BeatBoxify.Entity.*;

import java.util.List;

public interface UserRepository extends JpaRepository<Users, Integer>{
	//this method for finding the data by email this return the user object if user exist
	//the body for this method is auto generated by spring boot for communicating with db
	public Users findByEmail(String email);
	List<Users> findByPaid(boolean paid);
	public Users findByUsername(String username);
	List<Users> findByRoal(String roal);
}
