package com.tunehub.app.Repositories;

import org.springframework.data.jpa.repository.JpaRepository;
import com.tunehub.app.Entity.*;
import java.util.List;

public interface UserRepository extends JpaRepository<Users, Integer>{
	//this method for finding the data by email this return the user object if user exist
	//the body for this method is auto generated by spring boot for communicating with db
	public Users findByEmail(String email);
}
